name: pyciam
channels:
  - conda-forge
dependencies:
  - bottleneck
  - bokeh  # for use of dask dashboard
  - cartopy
  - cloudpathlib
  - distributed
  - flox
  - fsspec
  - geopandas
  - gitpython  # unmarked dependency of rhg_compute_tools
  - jupyterlab
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - papermill
  - pint-xarray
  - pip
  - python=3.14
  - requests
  - scikit-learn
  - scipy
  - tqdm
  - xarray
  - zarr
  - pip:
    - python-ciam
    - rhg_compute_tools
    - parameterize_jobs